AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lifescope migrations lambda function.

Resources:
  
  migrations:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        migrations:
          Type: Api
          Properties:
            Path: /migrations
            Method: any